# Generated by Django 6.0.4 on 2026-06-18 18:18

import complaint.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Nomor Aduan",
                    ),
                ),
                (
                    "judul",
                    models.CharField(max_length=255, verbose_name="Judul Pengaduan"),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("infrastruktur", "Infrastruktur"),
                            ("lingkungan", "Lingkungan"),
                            ("keamanan", "Keamanan"),
                            ("sosial", "Sosial"),
                            ("pelayanan_publik", "Pelayanan Publik"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "kategori_lain",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Kategori Lainnya"
                    ),
                ),
                (
                    "lokasi",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Lokasi Kejadian"
                    ),
                ),
                ("deskripsi", models.TextField(verbose_name="Deskripsi Lengkap")),
                (
                    "bukti_foto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=complaint.models.complaint_upload_path,
                        verbose_name="Bukti Foto/File",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Verifikasi"),
                            ("approved", "Diterima"),
                            ("rejected", "Ditolak"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "catatan_admin",
                    models.TextField(
                        blank=True, null=True, verbose_name="Catatan Admin"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaint_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pelapor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laporan Pengaduan",
                "verbose_name_plural": "Laporan Pengaduan",
                "ordering": ["-created_at"],
            },
        ),
    ]
