# Generated by Django 6.0.4 on 2026-05-10 13:02

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=account.models.avatar_upload_path,
                    ),
                ),
                (
                    "foto_ktp",
                    models.ImageField(
                        blank=True, null=True, upload_to=account.models.ktp_upload_path
                    ),
                ),
                (
                    "nik",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                (
                    "jenis_kelamin",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("tanggal_lahir", models.DateField(blank=True, null=True)),
                ("no_hp", models.CharField(blank=True, max_length=15, null=True)),
                ("alamat", models.CharField(blank=True, max_length=255, null=True)),
                ("rt", models.CharField(blank=True, max_length=3, null=True)),
                ("rw", models.CharField(blank=True, max_length=3, null=True)),
                ("dusun", models.CharField(blank=True, max_length=100, null=True)),
                ("pekerjaan", models.CharField(blank=True, max_length=100, null=True)),
                ("agama", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status_verifikasi",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("proses", "Proses"),
                            ("verified", "Verified"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("catatan_admin", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Pengguna",
                "verbose_name_plural": "Profil Pengguna",
            },
        ),
    ]
