# Generated by Django 6.0.4 on 2026-05-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="status_verifikasi",
            field=models.CharField(
                choices=[("pending", "Pending"), ("verified", "Verified")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
