# Generated by Django 6.0.4 on 2026-05-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('SEMUA', 'Semua'), ('PENGUMUMAN', 'Pengumuman'), ('KEGIATAN', 'Kegiatan'), ('LAYANAN', 'Layanan'), ('PERINGATAN', 'Peringatan')], default='PENGUMUMAN', max_length=20)),
                ('isi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='pengumuman/')),
                ('is_penting', models.BooleanField(default=False)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pengumuman',
            },
        ),
    ]
