# Generated by Django 6.0.4 on 2026-05-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StafDesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=120, verbose_name="Nama Lengkap")),
                (
                    "gelar_depan",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Gelar Depan"
                    ),
                ),
                (
                    "gelar_belakang",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Gelar Belakang"
                    ),
                ),
                ("jabatan", models.CharField(max_length=100, verbose_name="Jabatan")),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("Pimpinan", "Pimpinan"),
                            ("Sekretariat", "Sekretariat"),
                            ("Keuangan", "Keuangan"),
                            ("Pelayanan", "Pelayanan"),
                            ("Kesejahteraan", "Kesejahteraan"),
                            ("Pendidikan", "Pendidikan"),
                        ],
                        default="Pimpinan",
                        max_length=20,
                        verbose_name="Kategori / Divisi",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                (
                    "telepon",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Nomor Telepon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "tahun_mulai",
                    models.PositiveSmallIntegerField(verbose_name="Tahun Mulai"),
                ),
                (
                    "masih_aktif",
                    models.BooleanField(default=True, verbose_name="Masih Aktif?"),
                ),
                (
                    "tahun_selesai",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tahun Selesai (kosongkan jika masih aktif)",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_photos/",
                        verbose_name="Foto Profil",
                    ),
                ),
                (
                    "usaha",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Usaha / Unit Bisnis"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biografi Singkat")),
                (
                    "penghargaan",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Jumlah Penghargaan"
                    ),
                ),
                (
                    "urutan",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Urutan Tampil"
                    ),
                ),
                (
                    "aktif_tampil",
                    models.BooleanField(
                        default=True, verbose_name="Tampilkan di Website"
                    ),
                ),
                ("dibuat", models.DateTimeField(auto_now_add=True)),
                ("diperbarui", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staf Desa",
                "verbose_name_plural": "Staf Desa",
                "ordering": ["urutan", "nama"],
            },
        ),
    ]
