# Generated by Django 6.0.4 on 2026-05-13 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stafdesa",
            name="penghargaan",
        ),
        migrations.RemoveField(
            model_name="stafdesa",
            name="usaha",
        ),
        migrations.AddField(
            model_name="stafdesa",
            name="alamat",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Alamat / Dusun"
            ),
        ),
        migrations.AlterField(
            model_name="stafdesa",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Biografi"),
        ),
        migrations.CreateModel(
            name="Penghargaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judul",
                    models.CharField(max_length=200, verbose_name="Judul Penghargaan"),
                ),
                ("tahun", models.PositiveSmallIntegerField(verbose_name="Tahun")),
                (
                    "staf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penghargaan_list",
                        to="core.stafdesa",
                        verbose_name="Staf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penghargaan",
                "verbose_name_plural": "Penghargaan",
                "ordering": ["-tahun"],
            },
        ),
        migrations.CreateModel(
            name="UMKM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_usaha",
                    models.CharField(max_length=150, verbose_name="Nama Usaha"),
                ),
                (
                    "kategori_usaha",
                    models.CharField(
                        choices=[
                            ("Pertanian Organik", "Pertanian Organik"),
                            ("Perdagangan", "Perdagangan"),
                            ("Kerajinan", "Kerajinan"),
                            ("Kuliner", "Kuliner"),
                            ("Jasa", "Jasa"),
                            ("Peternakan", "Peternakan"),
                            ("Perikanan", "Perikanan"),
                            ("Teknologi", "Teknologi"),
                            ("Lainnya", "Lainnya"),
                        ],
                        default="Lainnya",
                        max_length=50,
                        verbose_name="Kategori Usaha",
                    ),
                ),
                (
                    "produk",
                    models.CharField(
                        blank=True,
                        help_text="Pisahkan dengan koma. Contoh: Beras organik, Sayuran segar, Pupuk kompos",
                        max_length=300,
                        verbose_name="Produk / Layanan",
                    ),
                ),
                (
                    "masih_aktif",
                    models.BooleanField(default=True, verbose_name="Masih Aktif?"),
                ),
                (
                    "staf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="umkm_list",
                        to="core.stafdesa",
                        verbose_name="Staf",
                    ),
                ),
            ],
            options={
                "verbose_name": "UMKM",
                "verbose_name_plural": "UMKM",
            },
        ),
    ]
