# Generated by Django 6.0.4 on 2026-06-25 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tag_galeriphoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="umkm",
            name="staf",
        ),
        migrations.AddField(
            model_name="stafdesa",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staf_desa",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Akun Pengguna (opsional)",
            ),
        ),
        migrations.DeleteModel(
            name="Penghargaan",
        ),
        migrations.DeleteModel(
            name="UMKM",
        ),
    ]
