# Generated by Django 6.0.4 on 2026-06-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True, verbose_name='Nama Tag')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('warna', models.CharField(default='green', help_text='Pilihan: green, blue, yellow, red, purple, orange', max_length=30, verbose_name='Warna Badge')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='GaleriPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeri/%Y/%m/', verbose_name='Foto')),
                ('judul', models.CharField(blank=True, max_length=120, verbose_name='Judul Foto')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Singkat')),
                ('bulan_tahun', models.DateField(help_text='Isi tanggal 1, yang ditampilkan hanya bulan & tahunnya', verbose_name='Bulan & Tahun')),
                ('urutan', models.PositiveSmallIntegerField(default=0, help_text='Angka lebih kecil tampil lebih dulu', verbose_name='Urutan Tampil')),
                ('ditampilkan', models.BooleanField(default=True, verbose_name='Tampilkan?')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='gallery.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Foto Galeri',
                'verbose_name_plural': 'Foto Galeri',
                'ordering': ['urutan', '-bulan_tahun'],
            },
        ),
    ]
