# Generated by Django 6.0.4 on 2026-05-18 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_usaha', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('alamat_usaha', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='pending', max_length=10)),
                ('nomor_pengajuan', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pemilik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='umkm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UMKM',
                'verbose_name_plural': 'Daftar UMKM',
            },
        ),
    ]
