# Generated by Django 6.0.4 on 2026-05-22 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkm',
            name='nomor_pengajuan',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('harga', models.PositiveIntegerField(help_text='Harga dalam rupiah')),
                ('harga_coret', models.PositiveIntegerField(blank=True, help_text='Harga sebelum diskon (opsional)', null=True)),
                ('kategori', models.CharField(choices=[('pertanian', 'Pertanian'), ('kerajinan', 'Kerajinan'), ('makanan_minuman', 'Makanan & Minuman'), ('jasa', 'Jasa'), ('perdagangan', 'Perdagangan'), ('herbal', 'Herbal'), ('peternakan', 'Peternakan')], default='perdagangan', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produk/')),
                ('tags', models.CharField(blank=True, help_text='Pisahkan tag dengan koma. Contoh: organik, segar, lokal', max_length=200, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='welfare.umkm')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Daftar Produk',
                'ordering': ['-created_at'],
            },
        ),
    ]
