# Generated by Django 6.0.4 on 2026-06-24 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0002_alter_umkm_nomor_pengajuan_produk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramBansos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('kategori', models.CharField(choices=[('pkh', 'PKH (Program Keluarga Harapan)'), ('blt', 'BLT Dana Desa'), ('bpnt', 'BPNT (Sembako)'), ('kip', 'KIP (Kartu Indonesia Pintar)'), ('lainnya', 'Lainnya')], default='lainnya', max_length=10)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('anggaran', models.BigIntegerField(default=0, help_text='Total anggaran dalam rupiah')),
                ('kuota_penerima', models.PositiveIntegerField(default=0, help_text='Maks jumlah penerima')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Bansos',
                'verbose_name_plural': 'Program Bansos',
                'ordering': ['-aktif', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='PengajuanBansos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_anggota', models.PositiveIntegerField(default=1, help_text='Jumlah anggota keluarga')),
                ('alasan', models.TextField(blank=True, help_text='Alasan pengajuan', null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=10)),
                ('catatan_staff', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_bansos', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan', to='welfare.programbansos')),
            ],
            options={
                'verbose_name': 'Pengajuan Bansos',
                'verbose_name_plural': 'Pengajuan Bansos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'program')},
            },
        ),
    ]
