# Generated by Django 6.0.4 on 2026-05-17 14:59

import django.db.models.deletion
import service.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoveLetterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Nomor Pengajuan",
                    ),
                ),
                (
                    "keperluan",
                    models.CharField(max_length=255, verbose_name="Alasan Pindah"),
                ),
                (
                    "jumlah_anggota",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Jumlah Anggota Keluarga Ikut"
                    ),
                ),
                (
                    "alamat_tujuan",
                    models.TextField(verbose_name="Alamat Lengkap Tujuan Pindah"),
                ),
                (
                    "file_kk",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="Kartu Keluarga",
                    ),
                ),
                (
                    "file_ktp",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="KTP-el Pemohon",
                    ),
                ),
                (
                    "file_pengantar",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="Surat Pengantar RT/RW",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Verifikasi"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Status Pengajuan",
                    ),
                ),
                (
                    "catatan_admin",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Catatan Admin (jika ditolak)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Pengajuan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Terakhir Diperbarui"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_letter_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pemohon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengajuan Surat Pindah",
                "verbose_name_plural": "Pengajuan Surat Pindah",
                "ordering": ["-created_at"],
            },
        ),
    ]
