# Generated by Django 6.0.4 on 2026-05-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moveletterrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Menunggu Verifikasi"),
                    ("approved", "Disetujui"),
                    ("rejected", "Ditolak"),
                    ("archived", "Diarsipkan"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="Status Pengajuan",
            ),
        ),
    ]
