# Generated by Django 6.0.4 on 2026-06-15 06:39

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_alter_moveletterrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="moveletterrequest",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tanggal Disetujui"
            ),
        ),
        migrations.AddField(
            model_name="moveletterrequest",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=service.models.letter_qr_upload_path,
                verbose_name="QR Code Verifikasi",
            ),
        ),
        migrations.AlterField(
            model_name="moveletterrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Menunggu Verifikasi"),
                    ("approved", "Disetujui"),
                    ("rejected", "Ditolak"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="Status Pengajuan",
            ),
        ),
    ]
