# Generated by Django 6.0.4 on 2026-06-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_moveletterrequest_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moveletterrequest",
            name="kecamatan",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Kecamatan"
            ),
        ),
        migrations.AddField(
            model_name="moveletterrequest",
            name="kelurahan",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Kelurahan/Desa"
            ),
        ),
        migrations.AddField(
            model_name="moveletterrequest",
            name="kota_kabupaten",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Kota/Kabupaten"
            ),
        ),
        migrations.AlterField(
            model_name="moveletterrequest",
            name="alamat_tujuan",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nama Jalan & RT/RW"
            ),
        ),
    ]
