# Generated by Django 6.0.4 on 2026-06-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_moveletterrequest_kecamatan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moveletterrequest",
            name="provinsi",
            field=models.CharField(blank=True, max_length=100, verbose_name="Provinsi"),
        ),
    ]
