# Generated by Django 6.0.4 on 2026-06-16 08:32

import django.db.models.deletion
import service.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_moveletterrequest_provinsi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DomicileLetterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Nomor Pengajuan",
                    ),
                ),
                (
                    "keperluan",
                    models.CharField(
                        max_length=255, verbose_name="Keperluan / Tujuan Surat"
                    ),
                ),
                (
                    "tujuan_instansi",
                    models.CharField(
                        max_length=255,
                        verbose_name="Ditujukan Kepada (Instansi Tujuan)",
                    ),
                ),
                (
                    "status_tempat_tinggal",
                    models.CharField(
                        choices=[
                            ("milik_sendiri", "Rumah Milik Sendiri"),
                            ("sewa_kontrak", "Sewa/Kontrak"),
                            ("menumpang", "Menumpang/Tinggal dengan Keluarga"),
                            ("dinas", "Rumah Dinas"),
                        ],
                        max_length=20,
                        verbose_name="Status Tempat Tinggal",
                    ),
                ),
                (
                    "lama_tinggal_tahun",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Lama Tinggal (Tahun)"
                    ),
                ),
                (
                    "lama_tinggal_bulan",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Lama Tinggal (Bulan)"
                    ),
                ),
                (
                    "file_kk",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="Kartu Keluarga",
                    ),
                ),
                (
                    "file_ktp",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="KTP-el Pemohon",
                    ),
                ),
                (
                    "file_pengantar",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="Surat Pengantar RT/RW",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=service.models.letter_qr_upload_path,
                        verbose_name="QR Code Verifikasi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Verifikasi"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Status Pengajuan",
                    ),
                ),
                (
                    "catatan_admin",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Catatan Admin (jika ditolak)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Pengajuan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Terakhir Diperbarui"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Disetujui"
                    ),
                ),
                (
                    "berlaku_hingga",
                    models.DateField(
                        blank=True, null=True, verbose_name="Berlaku Hingga"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domicile_letter_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pemohon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengajuan Surat Domisili",
                "verbose_name_plural": "Pengajuan Surat Domisili",
                "ordering": ["-created_at"],
            },
        ),
    ]
