# Generated by Django 6.0.4 on 2026-06-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_domicileletterrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="moveletterrequest",
            name="berlaku_hingga",
            field=models.DateField(
                blank=True, null=True, verbose_name="Berlaku Hingga"
            ),
        ),
    ]
