# Generated by Django 6.0.4 on 2026-06-16 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_moveletterrequest_berlaku_hingga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domicileletterrequest",
            name="lama_tinggal_bulan",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(11)],
                verbose_name="Lama Tinggal (Bulan)",
            ),
        ),
        migrations.AlterField(
            model_name="domicileletterrequest",
            name="lama_tinggal_tahun",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(10)],
                verbose_name="Lama Tinggal (Tahun)",
            ),
        ),
    ]
