# Generated by Django 6.0.4 on 2026-06-17 14:40

import django.db.models.deletion
import service.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_alter_domicileletterrequest_lama_tinggal_bulan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="domicileletterrequest",
            name="status_tempat_tinggal",
            field=models.CharField(
                choices=[
                    ("milik_sendiri", "Rumah Milik Sendairi"),
                    ("sewa_kontrak", "Sewa/Kontrak"),
                    ("menumpang", "Menumpang/Tinggal dengan Keluarga"),
                    ("dinas", "Rumah Dinas"),
                ],
                max_length=20,
                verbose_name="Status Tempat Tinggal",
            ),
        ),
        migrations.CreateModel(
            name="DeathLetterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Nomor Pengajuan",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=service.models.letter_qr_upload_path,
                        verbose_name="QR Code Verifikasi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Verifikasi"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Status Pengajuan",
                    ),
                ),
                (
                    "catatan_admin",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Catatan Admin (jika ditolak)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Pengajuan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Terakhir Diperbarui"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Disetujui"
                    ),
                ),
                (
                    "berlaku_hingga",
                    models.DateField(
                        blank=True, null=True, verbose_name="Berlaku Hingga"
                    ),
                ),
                (
                    "nama_almarhum",
                    models.CharField(
                        max_length=255, verbose_name="Nama Almarhum/Almarhumah"
                    ),
                ),
                (
                    "nik_almarhum",
                    models.CharField(
                        max_length=16, verbose_name="NIK Almarhum/Almarhumah"
                    ),
                ),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")],
                        max_length=1,
                        verbose_name="Jenis Kelamin",
                    ),
                ),
                (
                    "tempat_lahir",
                    models.CharField(
                        max_length=100, verbose_name="Tempat Lahir Almarhum"
                    ),
                ),
                (
                    "tanggal_lahir",
                    models.DateField(verbose_name="Tanggal Lahir Almarhum"),
                ),
                ("tanggal_kematian", models.DateField(verbose_name="Tanggal Kematian")),
                (
                    "tempat_kematian",
                    models.CharField(max_length=255, verbose_name="Tempat Kematian"),
                ),
                (
                    "penyebab_kematian",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Penyebab Kematian"
                    ),
                ),
                (
                    "hubungan_pelapor",
                    models.CharField(
                        max_length=100, verbose_name="Hubungan Pelapor dengan Almarhum"
                    ),
                ),
                (
                    "file_kk",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="Kartu Keluarga",
                    ),
                ),
                (
                    "file_ktp_almarhum",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="KTP-el Almarhum/Almarhumah",
                    ),
                ),
                (
                    "file_surat_dokter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=service.models.letter_upload_path,
                        verbose_name="Surat Keterangan Dokter/RS",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="death_letter_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pemohon (Pelapor)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengajuan Surat Kematian",
                "verbose_name_plural": "Pengajuan Surat Kematian",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
