# Generated by Django 6.0.4 on 2026-06-17 15:40

import django.db.models.deletion
import service.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0009_alter_domicileletterrequest_status_tempat_tinggal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthLetterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Nomor Pengajuan",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=service.models.letter_qr_upload_path,
                        verbose_name="QR Code Verifikasi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Verifikasi"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Status Pengajuan",
                    ),
                ),
                (
                    "catatan_admin",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Catatan Admin (jika ditolak)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Pengajuan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Terakhir Diperbarui"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Disetujui"
                    ),
                ),
                (
                    "berlaku_hingga",
                    models.DateField(
                        blank=True, null=True, verbose_name="Berlaku Hingga"
                    ),
                ),
                (
                    "nama_bayi",
                    models.CharField(max_length=255, verbose_name="Nama Bayi"),
                ),
                (
                    "jenis_kelamin_bayi",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")],
                        max_length=1,
                        verbose_name="Jenis Kelamin Bayi",
                    ),
                ),
                (
                    "tanggal_lahir_bayi",
                    models.DateField(verbose_name="Tanggal Lahir Bayi"),
                ),
                (
                    "tempat_lahir_bayi",
                    models.CharField(max_length=255, verbose_name="Tempat Lahir Bayi"),
                ),
                (
                    "anak_ke",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Anak Ke-"
                    ),
                ),
                (
                    "nama_ayah",
                    models.CharField(max_length=255, verbose_name="Nama Ayah"),
                ),
                ("nik_ayah", models.CharField(max_length=16, verbose_name="NIK Ayah")),
                ("nama_ibu", models.CharField(max_length=255, verbose_name="Nama Ibu")),
                ("nik_ibu", models.CharField(max_length=16, verbose_name="NIK Ibu")),
                (
                    "file_kk",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="Kartu Keluarga",
                    ),
                ),
                (
                    "file_ktp_ayah",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="KTP-el Ayah",
                    ),
                ),
                (
                    "file_ktp_ibu",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="KTP-el Ibu",
                    ),
                ),
                (
                    "file_surat_rs",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=service.models.letter_upload_path,
                        verbose_name="Surat Keterangan Lahir dari RS/Bidan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birth_letter_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pemohon (Pelapor)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengajuan Surat Kelahiran",
                "verbose_name_plural": "Pengajuan Surat Kelahiran",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
