# Generated by Django 6.0.4 on 2026-06-18 14:47

import django.db.models.deletion
import service.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0011_povertyletterrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessLetterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Nomor Pengajuan",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=service.models.letter_qr_upload_path,
                        verbose_name="QR Code Verifikasi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Verifikasi"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Status Pengajuan",
                    ),
                ),
                (
                    "catatan_admin",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Catatan Admin (jika ditolak)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Pengajuan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Terakhir Diperbarui"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Disetujui"
                    ),
                ),
                (
                    "berlaku_hingga",
                    models.DateField(
                        blank=True, null=True, verbose_name="Berlaku Hingga"
                    ),
                ),
                (
                    "nama_usaha",
                    models.CharField(max_length=255, verbose_name="Nama Usaha / Toko"),
                ),
                (
                    "jenis_usaha",
                    models.CharField(
                        choices=[
                            ("perdagangan", "Perdagangan / Toko"),
                            ("pertanian", "Pertanian / Perkebunan"),
                            ("perikanan", "Perikanan / Tambak"),
                            ("jasa", "Jasa / Servis"),
                            ("kerajinan", "Kerajinan / Industri Rumahan"),
                            ("kuliner", "Kuliner / Warung Makan"),
                            ("peternakan", "Peternakan"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Usaha",
                    ),
                ),
                (
                    "jenis_usaha_lain",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Jenis Usaha Lainnya"
                    ),
                ),
                (
                    "alamat_usaha",
                    models.CharField(
                        max_length=255, verbose_name="Alamat / Lokasi Usaha"
                    ),
                ),
                (
                    "lama_usaha_tahun",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Lama Usaha Berjalan (Tahun)"
                    ),
                ),
                (
                    "omset_perbulan",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Perkiraan Omset Per Bulan (Rp)"
                    ),
                ),
                (
                    "keperluan",
                    models.CharField(
                        choices=[
                            ("permodalan", "Pengajuan Modal / Pinjaman Usaha"),
                            ("izin_usaha", "Pengurusan Izin Usaha (SIUP/NIB)"),
                            ("bantuan_pemda", "Permohonan Bantuan Pemerintah"),
                            ("kemitraan", "Kemitraan / Kerja Sama Usaha"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                        verbose_name="Keperluan Surat",
                    ),
                ),
                (
                    "keperluan_lain",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Keperluan Lainnya"
                    ),
                ),
                (
                    "tujuan_instansi",
                    models.CharField(
                        max_length=255,
                        verbose_name="Ditujukan Kepada (Instansi Tujuan)",
                    ),
                ),
                (
                    "file_ktp",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="KTP-el Pemohon",
                    ),
                ),
                (
                    "file_kk",
                    models.FileField(
                        upload_to=service.models.letter_upload_path,
                        verbose_name="Kartu Keluarga",
                    ),
                ),
                (
                    "file_foto_usaha",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=service.models.letter_upload_path,
                        verbose_name="Foto Usaha / Tempat Usaha (Opsional)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_letter_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pemohon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengajuan Surat Keterangan Usaha",
                "verbose_name_plural": "Pengajuan Surat Keterangan Usaha",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
