# Generated by Django 6.0.4 on 2026-05-14 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AntreanKesehatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_pasien", models.CharField(max_length=150)),
                ("nik", models.CharField(max_length=16)),
                ("no_hp", models.CharField(max_length=15)),
                ("no_bpjs", models.CharField(blank=True, max_length=20, null=True)),
                ("keluhan", models.TextField()),
                (
                    "poli",
                    models.CharField(
                        choices=[
                            ("umum", "Poli Umum"),
                            ("gigi", "Poli Gigi"),
                            ("kia", "KIA / Kebidanan"),
                            ("lansia", "Poli Lansia"),
                            ("gizi", "Poli Gizi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tanggal_kunjungan", models.DateField()),
                ("nomor_antrean", models.PositiveIntegerField()),
                (
                    "kode_unik",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("estimasi_mulai", models.TimeField()),
                ("estimasi_selesai", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("menunggu", "Menunggu"),
                            ("selesai", "Selesai"),
                            ("expired", "Expired"),
                            ("batal", "Batal"),
                        ],
                        default="menunggu",
                        max_length=10,
                    ),
                ),
                ("diagnosa", models.CharField(blank=True, max_length=255, null=True)),
                ("resep_obat", models.TextField(blank=True, null=True)),
                ("catatan_nakes", models.TextField(blank=True, null=True)),
                ("waktu_selesai", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ditangani_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="antrean_ditangani",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antrean_kesehatan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Antrean Kesehatan",
                "verbose_name_plural": "Antrean Kesehatan",
                "ordering": ["tanggal_kunjungan", "nomor_antrean"],
                "unique_together": {("poli", "tanggal_kunjungan", "nomor_antrean")},
            },
        ),
    ]
