# Generated by Django 6.0.4 on 2026-05-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antreankesehatan",
            name="status",
            field=models.CharField(
                choices=[
                    ("menunggu", "Menunggu"),
                    ("hadir", "Hadir"),
                    ("selesai", "Selesai"),
                    ("expired", "Expired"),
                    ("batal", "Batal"),
                ],
                default="menunggu",
                max_length=10,
            ),
        ),
    ]
